spring:
  datasource:
    username: root
    password: dn960810
    #url?database?????????
    url: jdbc:mysql://localhost:3306/my_database?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
#    jdbc-type-for-null: null
    auto-mapping-behavior: full
  mapper-locations: classpath:com/xiaohei/springbootmyabtisplus/mapper/*.xml
  type-aliases-package: com.xiaohei.springbootmyabtisplus.entity
